SELECT
uid,
date,
device,
hitnum,
hit,
referral,
source,
mdm,
keyword,
landpg,
goalpg,
maker_name,
car_name,
-- off.jyoho_syuto_kubi as jyohosyutokubi,
off.SATEI_HANBAI_KUBUN as kubun,
off.SHIHYOU_DAIBUNRUI as shihyo_daibunrui,
off.SHIHYOU_SHOUBUNRUI as shihyo_syobunrui,
off.BAITAI_DAIBUNRUI as daibunrui_name,
off.BAITAI_SHOUBUNRUI as baitai,
off.S_TODOUFUKEN as todoufuken,
off.S_SHIKUCHOUSON as shikuchouson,
off.SHOUDAN_KUBUN as shoudan_kubun,
off.UKETSUKE_KUBUN as uketsuke_kubun,
off.TENPOMEI as tenpo,
off.KAITORI_SHOUDAN_SU as syodansu_kaitori,
off.HANBAI_SHOUDAN_SU as syodansu_hanbai,
off.KAITORI_SEIYAKUSU as seiyakusu_kaitori,
off.HANBAI_SEIYAKUSU as seiyakusu_hanbai,
-- off.jiki_name as jiki,
-- off.doki_name as doki,
-- off.seibetsu as seibetsu,
-- off.nenrei as nenrei,
-- off.kokyaku_tododufuken as kokyaku_todofuken,
-- off.kokyaku_shikucyoson as kokyaku_shikucyoson
FROM [kishita_risu_Sep.ga_GAID_Cardata] 
JOIN EACH [weekly_upload.informationbiz]  as off
ON carno = off.car_no
;
